spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    driver-class-name: org.postgresql.Driver
    username: erik
    password: erik123*

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: change-this-to-a-random-256-bit-secret-key-in-production
  expiration-ms: 86400000