server:
  port: 8083
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sender.senderyan.777@gmail.com
    password: hrjagsgqexbymdqi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: notifier
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-group
      auto-offset-reset: earliest # If the service restarts, read unread messages
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    redis:
      host: localhost
      port: 6379
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  tracing:
    sampling:
      probability: 1.0 # Trace 100% of requests
  zipkin:
    tracing:
      endpoint: http://zipkin-service:9411/api/v2/spans