apiVersion: v1
kind: Secret
metadata:
  name: messenger-secrets
type: Opaque
# stringData allows us to write plain text, and Kubernetes will automatically encrypt it into Base64 for us!
stringData:
  POSTGRES_USER: "erik"
  POSTGRES_PASSWORD: "erik123*"
  JWT_SECRET: "your-super-secret-jwt-key-that-needs-to-be-at-least-256-bits"
  EMAIL_PASSWORD: "hrjagsgqexbymdqi"