server:
  port: 8081
spring:
  application:
    name: messenger
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5433/chatdb
    driver-class-name: org.postgresql.Driver
    username: erik
    password: erik123*
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: change-this-to-a-random-256-bit-secret-key-in-production
  expiration-ms: 86400000
aws:
  s3:
    endpoint: http://localhost:4566
    region: us-east-1
    bucket: chat-images
    access-key: test
    secret-key: test